version: '3.3'

services:
  cf-server:
    build: ./cf-server
    command: cf-server
  nginx:
    build: ./nginx
    ports:
      - 80:80
      - 443:443
    volumes:
      - ./certbot/www:/var/www/certbot/:ro
      - ./certbot/conf/:/etc/nginx/ssl/:ro
    restart: always
    depends_on:
      - cf-server
  certbot:
    image: certbot/certbot:latest
    command: certonly --webroot --webroot-path "/var/www/certbot/" -d "creatorfollower.com" -d "www.creatorfollower.com" --register-unsafely-without-email --agree-tos --non-interactive --verbose
    volumes:
      - ./certbot/www/:/var/www/certbot/:rw
      - ./certbot/conf/:/etc/letsencrypt/:rw
